/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * e-commerce-api
 * e commerce api
 * OpenAPI spec version: 1.0.0
 */
export type UsersControllerFindParams = { filter?: UserFilter1 };

export type UsersControllerUpdateAllParams = { where?: { [key: string]: any } };

export type UsersControllerFindByIdParams = { filter?: UserFilter };

export type UsersControllerCountParams = { where?: { [key: string]: any } };

export type ProductsControllerFindParams = { filter?: ProductsFilter1 };

export type ProductsControllerUpdateAllParams = { where?: { [key: string]: any } };

export type ProductsControllerFindByIdParams = { filter?: ProductsFilter };

export type ProductsControllerCountParams = { where?: { [key: string]: any } };

export type InventoryControllerFindParams = { filter?: InventoryFilter1 };

export type InventoryControllerUpdateAllParams = { where?: { [key: string]: any } };

export type InventoryControllerCountParams = { where?: { [key: string]: any } };

export type CategoriesControllerFindParams = { filter?: CategoryFilter1 };

export type CategoriesControllerUpdateAllParams = { where?: { [key: string]: any } };

export type CategoriesControllerFindByIdParams = { filter?: CategoryFilter };

export type CategoriesControllerCountParams = { where?: { [key: string]: any } };

export type UserFilter1Where = { [key: string]: any };

export type UserFilter1Order = string | string[];

export interface UserFilter1 {
  offset?: number;
  limit?: number;
  skip?: number;
  order?: UserFilter1Order;
  where?: UserFilter1Where;
  fields?: UserFields;
}

export type UserFilterOrder = string | string[];

export interface UserFields {
  _id?: boolean;
  [key: string]: any;
 }

export interface UserFilter {
  offset?: number;
  limit?: number;
  skip?: number;
  order?: UserFilterOrder;
  fields?: UserFields;
}

export type ProductsFilter1Where = { [key: string]: any };

export type ProductsFilter1Order = string | string[];

export interface ProductsFilter1 {
  offset?: number;
  limit?: number;
  skip?: number;
  order?: ProductsFilter1Order;
  where?: ProductsFilter1Where;
  fields?: ProductsFields;
}

export type ProductsFilterOrder = string | string[];

export interface ProductsFields {
  _id?: boolean;
}

export interface ProductsFilter {
  offset?: number;
  limit?: number;
  skip?: number;
  order?: ProductsFilterOrder;
  fields?: ProductsFields;
}

export type PingResponseHeaders = {
  'Content-Type'?: string;
  [key: string]: any;
 };

export interface PingResponse {
  greeting?: string;
  date?: string;
  url?: string;
  headers?: PingResponseHeaders;
}

export type InventoryFilter1Where = { [key: string]: any };

export type InventoryFilter1Order = string | string[];

export type InventoryFilterOrder = string | string[];

export interface InventoryFields {
  _id?: boolean;
}

export interface InventoryFilter1 {
  offset?: number;
  limit?: number;
  skip?: number;
  order?: InventoryFilter1Order;
  where?: InventoryFilter1Where;
  fields?: InventoryFields;
}

export interface InventoryFilter {
  offset?: number;
  limit?: number;
  skip?: number;
  order?: InventoryFilterOrder;
  fields?: InventoryFields;
}

export type InventoryControllerFindByIdParams = { filter?: InventoryFilter };

export type CategoryFilter1Where = { [key: string]: any };

export type CategoryFilter1Order = string | string[];

export interface CategoryFilter1 {
  offset?: number;
  limit?: number;
  skip?: number;
  order?: CategoryFilter1Order;
  where?: CategoryFilter1Where;
  fields?: CategoryFields;
}

export type CategoryFilterOrder = string | string[];

export interface CategoryFields {
  _id?: boolean;
}

export interface CategoryFilter {
  offset?: number;
  limit?: number;
  skip?: number;
  order?: CategoryFilterOrder;
  fields?: CategoryFields;
}

export interface LoopbackCount {
  count?: number;
}

/**
 * (tsType: Partial<User>, schemaOptions: { partial: true })
 */
export interface UserPartial {
  _id?: string;
  [key: string]: any;
 }

/**
 * (tsType: UserWithRelations, schemaOptions: { includeRelations: true })
 */
export interface UserWithRelations {
  _id?: string;
  [key: string]: any;
 }

/**
 * (tsType: Omit<User, '_id'>, schemaOptions: { title: 'NewUser', exclude: [ '_id' ] })
 */
export interface NewUser { [key: string]: any }

export interface User {
  _id?: string;
  [key: string]: any;
 }

/**
 * (tsType: Partial<Products>, schemaOptions: { partial: true })
 */
export interface ProductsPartial {
  _id?: string;
}

/**
 * (tsType: ProductsWithRelations, schemaOptions: { includeRelations: true })
 */
export interface ProductsWithRelations {
  _id?: string;
}

/**
 * (tsType: Omit<Products, '_id'>, schemaOptions: { title: 'NewProducts', exclude: [ '_id' ] })
 */
export interface NewProducts { [key: string]: any }

export interface Products {
  _id?: string;
}

/**
 * (tsType: Partial<Inventory>, schemaOptions: { partial: true })
 */
export interface InventoryPartial {
  _id?: string;
}

/**
 * (tsType: InventoryWithRelations, schemaOptions: { includeRelations: true })
 */
export interface InventoryWithRelations {
  _id?: string;
}

/**
 * (tsType: Omit<Inventory, '_id'>, schemaOptions: { title: 'NewInventory', exclude: [ '_id' ] })
 */
export interface NewInventory { [key: string]: any }

export interface Inventory {
  _id?: string;
}

/**
 * (tsType: Partial<Category>, schemaOptions: { partial: true })
 */
export interface CategoryPartial {
  _id?: string;
}

/**
 * (tsType: CategoryWithRelations, schemaOptions: { includeRelations: true })
 */
export interface CategoryWithRelations {
  _id?: string;
}

/**
 * (tsType: Omit<Category, '_id'>, schemaOptions: { title: 'NewCategory', exclude: [ '_id' ] })
 */
export interface NewCategory { [key: string]: any }

export interface Category {
  _id?: string;
}

