/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * e-commerce-api
 * e commerce api
 * OpenAPI spec version: 1.0.0
 */
export type PingResponseHeaders = {
  'Content-Type'?: string;
  [key: string]: any;
 };

export interface PingResponse {
  greeting?: string;
  date?: string;
  url?: string;
  headers?: PingResponseHeaders;
}

