/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Ecommerce API
 * API for e commerce App
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useMutation
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'
import type {
  LoopbackCount,
  InventoryControllerCountParams,
  Inventory,
  InventoryPartial,
  InventoryWithRelations,
  InventoryControllerFindByIdParams,
  NewInventory,
  InventoryControllerUpdateAllParams,
  InventoryControllerFindParams
} from './ecommerceApi.schemas'
import { customInstance } from '../mutator/custom-instance'
import type { ErrorType } from '../mutator/custom-instance'



export const inventoryControllerCount = (
    params?: InventoryControllerCountParams,
 signal?: AbortSignal
) => {
      return customInstance<LoopbackCount>(
      {url: `/inventories/count`, method: 'get',
        params, signal
    },
      );
    }
  

export const getInventoryControllerCountQueryKey = (params?: InventoryControllerCountParams,) => [`/inventories/count`, ...(params ? [params]: [])];

    
export type InventoryControllerCountQueryResult = NonNullable<Awaited<ReturnType<typeof inventoryControllerCount>>>
export type InventoryControllerCountQueryError = ErrorType<unknown>

export const useInventoryControllerCount = <TData = Awaited<ReturnType<typeof inventoryControllerCount>>, TError = ErrorType<unknown>>(
 params?: InventoryControllerCountParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerCount>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInventoryControllerCountQueryKey(params);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof inventoryControllerCount>>> = ({ signal }) => inventoryControllerCount(params, signal);

  const query = useQuery<Awaited<ReturnType<typeof inventoryControllerCount>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const inventoryControllerReplaceById = (
    id: string,
    inventory: Inventory,
 ) => {
      return customInstance<void>(
      {url: `/inventories/${id}`, method: 'put',
      headers: {'Content-Type': 'application/json', },
      data: inventory
    },
      );
    }
  


    export type InventoryControllerReplaceByIdMutationResult = NonNullable<Awaited<ReturnType<typeof inventoryControllerReplaceById>>>
    export type InventoryControllerReplaceByIdMutationBody = Inventory
    export type InventoryControllerReplaceByIdMutationError = ErrorType<unknown>

    export const useInventoryControllerReplaceById = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inventoryControllerReplaceById>>, TError,{id: string;data: Inventory}, TContext>, }
) => {
      const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inventoryControllerReplaceById>>, {id: string;data: Inventory}> = (props) => {
          const {id,data} = props ?? {};

          return  inventoryControllerReplaceById(id,data,)
        }

      return useMutation<Awaited<ReturnType<typeof inventoryControllerReplaceById>>, TError, {id: string;data: Inventory}, TContext>(mutationFn, mutationOptions)
    }
    export const inventoryControllerUpdateById = (
    id: string,
    inventoryPartial: InventoryPartial,
 ) => {
      return customInstance<void>(
      {url: `/inventories/${id}`, method: 'patch',
      headers: {'Content-Type': 'application/json', },
      data: inventoryPartial
    },
      );
    }
  


    export type InventoryControllerUpdateByIdMutationResult = NonNullable<Awaited<ReturnType<typeof inventoryControllerUpdateById>>>
    export type InventoryControllerUpdateByIdMutationBody = InventoryPartial
    export type InventoryControllerUpdateByIdMutationError = ErrorType<unknown>

    export const useInventoryControllerUpdateById = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inventoryControllerUpdateById>>, TError,{id: string;data: InventoryPartial}, TContext>, }
) => {
      const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inventoryControllerUpdateById>>, {id: string;data: InventoryPartial}> = (props) => {
          const {id,data} = props ?? {};

          return  inventoryControllerUpdateById(id,data,)
        }

      return useMutation<Awaited<ReturnType<typeof inventoryControllerUpdateById>>, TError, {id: string;data: InventoryPartial}, TContext>(mutationFn, mutationOptions)
    }
    export const inventoryControllerFindById = (
    id: string,
    params?: InventoryControllerFindByIdParams,
 signal?: AbortSignal
) => {
      return customInstance<InventoryWithRelations>(
      {url: `/inventories/${id}`, method: 'get',
        params, signal
    },
      );
    }
  

export const getInventoryControllerFindByIdQueryKey = (id: string,
    params?: InventoryControllerFindByIdParams,) => [`/inventories/${id}`, ...(params ? [params]: [])];

    
export type InventoryControllerFindByIdQueryResult = NonNullable<Awaited<ReturnType<typeof inventoryControllerFindById>>>
export type InventoryControllerFindByIdQueryError = ErrorType<unknown>

export const useInventoryControllerFindById = <TData = Awaited<ReturnType<typeof inventoryControllerFindById>>, TError = ErrorType<unknown>>(
 id: string,
    params?: InventoryControllerFindByIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindById>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInventoryControllerFindByIdQueryKey(id,params);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof inventoryControllerFindById>>> = ({ signal }) => inventoryControllerFindById(id,params, signal);

  const query = useQuery<Awaited<ReturnType<typeof inventoryControllerFindById>>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const inventoryControllerDeleteById = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/inventories/${id}`, method: 'delete'
    },
      );
    }
  


    export type InventoryControllerDeleteByIdMutationResult = NonNullable<Awaited<ReturnType<typeof inventoryControllerDeleteById>>>
    
    export type InventoryControllerDeleteByIdMutationError = ErrorType<unknown>

    export const useInventoryControllerDeleteById = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inventoryControllerDeleteById>>, TError,{id: string}, TContext>, }
) => {
      const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inventoryControllerDeleteById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  inventoryControllerDeleteById(id,)
        }

      return useMutation<Awaited<ReturnType<typeof inventoryControllerDeleteById>>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    export const inventoryControllerCreate = (
    newInventory: NewInventory,
 ) => {
      return customInstance<Inventory>(
      {url: `/inventories`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: newInventory
    },
      );
    }
  


    export type InventoryControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof inventoryControllerCreate>>>
    export type InventoryControllerCreateMutationBody = NewInventory
    export type InventoryControllerCreateMutationError = ErrorType<unknown>

    export const useInventoryControllerCreate = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inventoryControllerCreate>>, TError,{data: NewInventory}, TContext>, }
) => {
      const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inventoryControllerCreate>>, {data: NewInventory}> = (props) => {
          const {data} = props ?? {};

          return  inventoryControllerCreate(data,)
        }

      return useMutation<Awaited<ReturnType<typeof inventoryControllerCreate>>, TError, {data: NewInventory}, TContext>(mutationFn, mutationOptions)
    }
    export const inventoryControllerUpdateAll = (
    inventoryPartial: InventoryPartial,
    params?: InventoryControllerUpdateAllParams,
 ) => {
      return customInstance<LoopbackCount>(
      {url: `/inventories`, method: 'patch',
      headers: {'Content-Type': 'application/json', },
      data: inventoryPartial,
        params
    },
      );
    }
  


    export type InventoryControllerUpdateAllMutationResult = NonNullable<Awaited<ReturnType<typeof inventoryControllerUpdateAll>>>
    export type InventoryControllerUpdateAllMutationBody = InventoryPartial
    export type InventoryControllerUpdateAllMutationError = ErrorType<unknown>

    export const useInventoryControllerUpdateAll = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inventoryControllerUpdateAll>>, TError,{data: InventoryPartial;params?: InventoryControllerUpdateAllParams}, TContext>, }
) => {
      const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inventoryControllerUpdateAll>>, {data: InventoryPartial;params?: InventoryControllerUpdateAllParams}> = (props) => {
          const {data,params} = props ?? {};

          return  inventoryControllerUpdateAll(data,params,)
        }

      return useMutation<Awaited<ReturnType<typeof inventoryControllerUpdateAll>>, TError, {data: InventoryPartial;params?: InventoryControllerUpdateAllParams}, TContext>(mutationFn, mutationOptions)
    }
    export const inventoryControllerFind = (
    params?: InventoryControllerFindParams,
 signal?: AbortSignal
) => {
      return customInstance<InventoryWithRelations[]>(
      {url: `/inventories`, method: 'get',
        params, signal
    },
      );
    }
  

export const getInventoryControllerFindQueryKey = (params?: InventoryControllerFindParams,) => [`/inventories`, ...(params ? [params]: [])];

    
export type InventoryControllerFindQueryResult = NonNullable<Awaited<ReturnType<typeof inventoryControllerFind>>>
export type InventoryControllerFindQueryError = ErrorType<unknown>

export const useInventoryControllerFind = <TData = Awaited<ReturnType<typeof inventoryControllerFind>>, TError = ErrorType<unknown>>(
 params?: InventoryControllerFindParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFind>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInventoryControllerFindQueryKey(params);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof inventoryControllerFind>>> = ({ signal }) => inventoryControllerFind(params, signal);

  const query = useQuery<Awaited<ReturnType<typeof inventoryControllerFind>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

