/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * e-commerce-api
 * e commerce api
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'
import type {
  PingResponse
} from './ecommerceApi.schemas'



export const pingControllerPing = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PingResponse>> => {
    return axios.get(
      `/ping`,options
    );
  }


export const getPingControllerPingQueryKey = () => [`/ping`];

    
export type PingControllerPingQueryResult = NonNullable<Awaited<ReturnType<typeof pingControllerPing>>>
export type PingControllerPingQueryError = AxiosError<unknown>

export const usePingControllerPing = <TData = Awaited<ReturnType<typeof pingControllerPing>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof pingControllerPing>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPingControllerPingQueryKey();

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof pingControllerPing>>> = ({ signal }) => pingControllerPing({ signal, ...axiosOptions });

  const query = useQuery<Awaited<ReturnType<typeof pingControllerPing>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

